### ISSUE TITLE
Use pre-process step instead?

### ISSUE THREAD

**Issue by augustoroman** [alecthomas/template#1]
Rather than forking text/template, why not pre-process the template to strip offending newlines?

Something like: http://play.golang.org/p/1hixWanQAV
(or use text/template/parse if you really want to be sure)

**Comment by alecthomas** [comment]
Because pre-processing basically requires writing a complete parser to ensure correctness. eg. in your example, a literal `}}\` anywhere in the template will be stripped, even if it is not part of a template expression.

As for using text/template/parse, this was the first thing I looked at but, as the name implies, it produces a parse tree. If the lexer were exposed it would be relatively trivial to transform the lexed tokens, but the parse tree is much more difficult to process. It was far simpler to just fork it and patch.
